/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nldn.h"

bool_t
xdr_obs(register XDR *xdrs, obs *objp)
{

	register long *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE(xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_int(xdrs, &objp->tsec))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->tnsec))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->lat))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->lon))
				return (FALSE);
			if (!xdr_short(xdrs, &objp->sgnl))
				return (FALSE);

		} else {
			IXDR_PUT_LONG(buf, objp->tsec);
			IXDR_PUT_LONG(buf, objp->tnsec);
			IXDR_PUT_LONG(buf, objp->lat);
			IXDR_PUT_LONG(buf, objp->lon);
			IXDR_PUT_SHORT(buf, objp->sgnl);
		}
		if (!xdr_char(xdrs, &objp->mult))
			return (FALSE);
		if (!xdr_char(xdrs, &objp->semimaj))
			return (FALSE);
		if (!xdr_char(xdrs, &objp->eccent))
			return (FALSE);
		if (!xdr_char(xdrs, &objp->angle))
			return (FALSE);
		if (!xdr_char(xdrs, &objp->chisqr))
			return (FALSE);
		return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE(xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_int(xdrs, &objp->tsec))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->tnsec))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->lat))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->lon))
				return (FALSE);
			if (!xdr_short(xdrs, &objp->sgnl))
				return (FALSE);

		} else {
			objp->tsec = IXDR_GET_LONG(buf);
			objp->tnsec = IXDR_GET_LONG(buf);
			objp->lat = IXDR_GET_LONG(buf);
			objp->lon = IXDR_GET_LONG(buf);
			objp->sgnl = IXDR_GET_SHORT(buf);
		}
		if (!xdr_char(xdrs, &objp->mult))
			return (FALSE);
		if (!xdr_char(xdrs, &objp->semimaj))
			return (FALSE);
		if (!xdr_char(xdrs, &objp->eccent))
			return (FALSE);
		if (!xdr_char(xdrs, &objp->angle))
			return (FALSE);
		if (!xdr_char(xdrs, &objp->chisqr))
			return (FALSE);
		return (TRUE);
	}

	if (!xdr_int(xdrs, &objp->tsec))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->tnsec))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->lat))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->lon))
		return (FALSE);
	if (!xdr_short(xdrs, &objp->sgnl))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->mult))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->semimaj))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->eccent))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->angle))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->chisqr))
		return (FALSE);
	return (TRUE);
}
