." $Id: zlibg2gini.1,v 1.0 2004/09/16 10:00:00 yoksas Exp $
.TH ZLIBG2GINI 1 "2004/09/16 10:00:00 $"
.SH NAME
zlibg2gini \- Unidata LDM decoder for ZLIB-compressed NOAAPORT GINI imagery
.SH SYNOPSIS
.HP
.ft B
zlibg2gini
.nh
\%[-f\ \fIZLIBfile\fP]
\%[-v]
\%[-x]
\%[-l\ \fIlogpath\fP]
\%\fIIMGfile\fP
.hy
.ft
.SH DESCRIPTION
.LP
This program is an LDM decoder for NOAAPORT image data of type \fBGINI\fP
that has been ZLIB-compressed.
It reads a ZLIB-compressed GINI data product from standard input or from a file
and decodes that data into a NOAAPORT format GINI file.
.LP
This program can be invoked by an entry in the LDM \fBpqact.conf\fP
configuration file with a pattern similar to the following:
.sp
.nf
#
# NOAAPORT ZLIB-compressed images decoded into GINI files
#
FNEXRAD	^satz/ch[0-9]/.*/(.*)/([12][0-9])([0-9][0-9])([01][0-9])([0-3][0-9]) ([0-2][0-9])([0-5][0-9])/(.*)/(.*km)/
	PIPE	-close
	zlibg2gini -vl logs/ldm-mcidas.log
	/data/ldm/gempak/images/sat/\\8/\\9/\\1/\\1_\\2\\3\\4\\5_\\6\\7

.fi
.RE
.LP
Since Unidata-supported display and analysis applications (GEMPAK, the IDF,
and McIDAS) can read the ZLIB-compressed images directly, use of this decoder
should be infrequent.
.fi
.RE
.LP
This program can also be invoked as a
stand-alone program, outside the LDM environment.

.SH FLAGS
.TP
.BI "-f " ZLIBfile
Pathname for input ZLIB compressed GINI file (default is stdin)
.TP
.B "-h "
Print help information, then exit the program.
.TP
.B -v
Verbose logging.
Informative messages (level LOG_INFO) are logged.
By default, only messages of severity LOG_NOTICE and greater are
logged. See the Unidata  LDM Site  Manager's  Guide  for more information on 
message logging.
.TP
.B -x
Debug logging.
Debugging messages (level LOG_DEBUG) are logged. See the Unidata  LDM Site  
Manager's  Guide  for more information on message logging.
.TP
.BI "-l " logpath
Log file pathname.
The program uses Unidata's \fBulog\fP(3) package to write error and diagnostic
messages.
The default is to write to the \fBsyslogd\fP(8) daemon.  If this option is
specified, however, then messages will be written to the file
\fIlogpath\fP unless that pathname is "-", in which case all messages will be
written to standard error.

.RE
.SH NOTES
.LP
.RE
.SH "SEE ALSO"
.LP
.BR ~ldm-mcidas/etc/ldm-mcidas-pqact.conf,
.BR ldmd (1),
.BR ulog (3),
.BR syslogd (8).
